env:
  browser: true
  node: true
extends:
  - "eslint:recommended"
  #  - "@nuxtjs/eslint-config-typescript"
  - "plugin:vue/recommended"
  - "prettier"
parser: "vue-eslint-parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - vue
rules: {}
